In [ ]:
apsit = """The A. P. Shah Institute of Technology (APSIT), managed by the Parshvanath Charitable Trust (PCT), is committed to providing top-notch technical education.
Founded in 1993 by Late Shri Ashokbhai Shah, PCT aims to offer world-class facilities and an environment conducive to learning.
APSIT boasts experienced faculty and exemplary infrastructure, ensuring the holistic development of students.
The Training and Placement department facilitates career opportunities, organizing campus recruitments and offering training in soft skills and aptitude.
 Through various activities and programs, APSIT aims to bridge the gap between academia and industry, preparing students to excel in the corporate world.
 Located in Thane, Maharashtra, APSIT is easily accessible by public transportation."""

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([apsit])


In [ ]:
tokenizer.word_index

{'and': 1,
 'the': 2,
 'to': 3,
 'apsit': 4,
 'in': 5,
 'by': 6,
 'shah': 7,
 'of': 8,
 'pct': 9,
 'is': 10,
 'aims': 11,
 'world': 12,
 'students': 13,
 'training': 14,
 'a': 15,
 'p': 16,
 'institute': 17,
 'technology': 18,
 'managed': 19,
 'parshvanath': 20,
 'charitable': 21,
 'trust': 22,
 'committed': 23,
 'providing': 24,
 'top': 25,
 'notch': 26,
 'technical': 27,
 'education': 28,
 'founded': 29,
 '1993': 30,
 'late': 31,
 'shri': 32,
 'ashokbhai': 33,
 'offer': 34,
 'class': 35,
 'facilities': 36,
 'an': 37,
 'environment': 38,
 'conducive': 39,
 'learning': 40,
 'boasts': 41,
 'experienced': 42,
 'faculty': 43,
 'exemplary': 44,
 'infrastructure': 45,
 'ensuring': 46,
 'holistic': 47,
 'development': 48,
 'placement': 49,
 'department': 50,
 'facilitates': 51,
 'career': 52,
 'opportunities': 53,
 'organizing': 54,
 'campus': 55,
 'recruitments': 56,
 'offering': 57,
 'soft': 58,
 'skills': 59,
 'aptitude': 60,
 'through': 61,
 'various': 62,
 'activities': 63,
 'programs':

In [ ]:
len(tokenizer.word_index)

79

In [ ]:
for sentence in apsit.split('\n'):
  print(sentence)

The A. P. Shah Institute of Technology (APSIT), managed by the Parshvanath Charitable Trust (PCT), is committed to providing top-notch technical education.
Founded in 1993 by Late Shri Ashokbhai Shah, PCT aims to offer world-class facilities and an environment conducive to learning.
APSIT boasts experienced faculty and exemplary infrastructure, ensuring the holistic development of students.
The Training and Placement department facilitates career opportunities, organizing campus recruitments and offering training in soft skills and aptitude.
 Through various activities and programs, APSIT aims to bridge the gap between academia and industry, preparing students to excel in the corporate world.
 Located in Thane, Maharashtra, APSIT is easily accessible by public transportation.


In [ ]:
for sentence in apsit.split('\n'):
  print(tokenizer.texts_to_sequences([sentence])[0])


[2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2, 20, 21, 22, 9, 10, 23, 3, 24, 25, 26, 27, 28]
[29, 5, 30, 6, 31, 32, 33, 7, 9, 11, 3, 34, 12, 35, 36, 1, 37, 38, 39, 3, 40]
[4, 41, 42, 43, 1, 44, 45, 46, 2, 47, 48, 8, 13]
[2, 14, 1, 49, 50, 51, 52, 53, 54, 55, 56, 1, 57, 14, 5, 58, 59, 1, 60]
[61, 62, 63, 1, 64, 4, 11, 3, 65, 2, 66, 67, 68, 1, 69, 70, 13, 3, 71, 5, 2, 72, 12]
[73, 5, 74, 75, 4, 10, 76, 77, 6, 78, 79]


In [ ]:
input_sequences = []
for sentence in apsit.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [ ]:
input_sequences

[[2, 15],
 [2, 15, 16],
 [2, 15, 16, 7],
 [2, 15, 16, 7, 17],
 [2, 15, 16, 7, 17, 8],
 [2, 15, 16, 7, 17, 8, 18],
 [2, 15, 16, 7, 17, 8, 18, 4],
 [2, 15, 16, 7, 17, 8, 18, 4, 19],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2, 20],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2, 20, 21],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2, 20, 21, 22],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2, 20, 21, 22, 9],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2, 20, 21, 22, 9, 10],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2, 20, 21, 22, 9, 10, 23],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2, 20, 21, 22, 9, 10, 23, 3],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2, 20, 21, 22, 9, 10, 23, 3, 24],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2, 20, 21, 22, 9, 10, 23, 3, 24, 25],
 [2, 15, 16, 7, 17, 8, 18, 4, 19, 6, 2, 20, 21, 22, 9, 10, 23, 3, 24, 25, 26],
 [2,
  15,
  16,
  7,
  17,
  8,
  18,
  4,
  19,
  6,
  2,
  20,
  21,
  22,
  9,
  10,
  23,
  3,
  24,
  25,
  26,
  27

In [ ]:
[len(x) for x in input_sequences]

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11]

In [ ]:
max([len(x) for x in input_sequences])

23

In [ ]:
max_len = max([len(x) for x in input_sequences])

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')


In [ ]:
padded_input_sequences

array([[ 0,  0,  0, ...,  0,  2, 15],
       [ 0,  0,  0, ...,  2, 15, 16],
       [ 0,  0,  0, ..., 15, 16,  7],
       ...,
       [ 0,  0,  0, ..., 76, 77,  6],
       [ 0,  0,  0, ..., 77,  6, 78],
       [ 0,  0,  0, ...,  6, 78, 79]], dtype=int32)

In [ ]:
padded_input_sequences[:,:-1]

array([[ 0,  0,  0, ...,  0,  0,  2],
       [ 0,  0,  0, ...,  0,  2, 15],
       [ 0,  0,  0, ...,  2, 15, 16],
       ...,
       [ 0,  0,  0, ..., 10, 76, 77],
       [ 0,  0,  0, ..., 76, 77,  6],
       [ 0,  0,  0, ..., 77,  6, 78]], dtype=int32)

In [ ]:
X = padded_input_sequences[:,:-1]

In [ ]:
padded_input_sequences[:,-1]

array([15, 16,  7, 17,  8, 18,  4, 19,  6,  2, 20, 21, 22,  9, 10, 23,  3,
       24, 25, 26, 27, 28,  5, 30,  6, 31, 32, 33,  7,  9, 11,  3, 34, 12,
       35, 36,  1, 37, 38, 39,  3, 40, 41, 42, 43,  1, 44, 45, 46,  2, 47,
       48,  8, 13, 14,  1, 49, 50, 51, 52, 53, 54, 55, 56,  1, 57, 14,  5,
       58, 59,  1, 60, 62, 63,  1, 64,  4, 11,  3, 65,  2, 66, 67, 68,  1,
       69, 70, 13,  3, 71,  5,  2, 72, 12,  5, 74, 75,  4, 10, 76, 77,  6,
       78, 79], dtype=int32)

In [ ]:
y = padded_input_sequences[:,-1]

In [ ]:
X.shape

(104, 22)

In [ ]:
y.shape

(104,)

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=555)

In [ ]:
y.shape

(104, 555)

In [ ]:
y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
model = Sequential()
model.add(Embedding(555, 100, input_length=22))
model.add(LSTM(150))
model.add(Dense(555, activation='softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 22, 100)           55500     
                                                                 
 lstm_1 (LSTM)               (None, 150)               150600    
                                                                 
 dense_1 (Dense)             (None, 555)               83805     
                                                                 
Total params: 289905 (1.11 MB)
Trainable params: 289905 (1.11 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
4/4 [==============================] - 3s 34ms/step - loss: 6.3168 - accuracy: 0.0000e+00
Epoch 2/100
4/4 [==============================] - 0s 33ms/step - loss: 6.2848 - accuracy: 0.0481
Epoch 3/100
4/4 [==============================] - 0s 32ms/step - loss: 6.1580 - accuracy: 0.0577
Epoch 4/100
4/4 [==============================] - 0s 32ms/step - loss: 5.5429 - accuracy: 0.0673
Epoch 5/100
4/4 [==============================] - 0s 33ms/step - loss: 4.9530 - accuracy: 0.0192
Epoch 6/100
4/4 [==============================] - 0s 33ms/step - loss: 4.5923 - accuracy: 0.0673
Epoch 7/100
4/4 [==============================] - 0s 32ms/step - loss: 4.4107 - accuracy: 0.0673
Epoch 8/100
4/4 [==============================] - 0s 33ms/step - loss: 4.3210 - accuracy: 0.0673
Epoch 9/100
4/4 [==============================] - 0s 35ms/step - loss: 4.2702 - accuracy: 0.0673
Epoch 10/100
4/4 [==============================] - 0s 33ms/step - loss: 4.2385 - accuracy: 0.0673
Epoch 11/100
4/

In [ ]:
text = "shah"
tokenizer.texts_to_sequences([text])[0]

[7]

In [ ]:
token_text = tokenizer.texts_to_sequences([text])[0]

In [ ]:
pad_sequences([token_text], maxlen=50, padding='pre')


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 7]], dtype=int32)

In [ ]:
padded_token_text = pad_sequences([token_text], maxlen=22, padding='pre')

In [ ]:
model.predict(padded_token_text)

1/1 [==============================] - 0s 38ms/step


array([[1.34878483e-05, 8.72612372e-02, 8.27098545e-03, 6.07400537e-02,
        1.22427773e-02, 4.99772839e-02, 7.52938166e-03, 1.34849166e-02,
        7.36732362e-03, 1.10687148e-02, 9.09767114e-03, 7.18918489e-03,
        5.14465980e-02, 3.05788927e-02, 4.00861800e-02, 1.20739210e-02,
        5.74039621e-03, 3.57781700e-03, 9.54058114e-03, 3.56487045e-03,
        1.86209343e-02, 5.66943269e-03, 6.69877930e-03, 4.76670824e-03,
        3.42834811e-03, 3.34357657e-03, 7.94922188e-03, 4.01211670e-03,
        3.13424738e-03, 1.36731669e-05, 3.87483137e-03, 3.32392263e-03,
        2.87048006e-03, 6.66079950e-03, 4.55698231e-03, 1.32178850e-02,
        6.44753128e-03, 3.53410793e-03, 1.19702797e-02, 7.83865806e-03,
        5.20663755e-03, 3.73005122e-03, 1.91329571e-03, 2.88587948e-03,
        1.58212672e-03, 7.59755122e-03, 6.72801211e-03, 2.15653386e-02,
        1.56022087e-02, 5.72772510e-03, 5.13242930e-03, 1.36917783e-02,
        5.11782616e-03, 2.57944106e-03, 1.48080559e-02, 1.744568

In [ ]:
model.predict(padded_token_text).shape

1/1 [==============================] - 0s 25ms/step


(1, 555)

In [ ]:
import numpy as np


In [ ]:
np.argmax(model.predict(padded_token_text))

1/1 [==============================] - 0s 24ms/step


9

In [ ]:
tokenizer.word_index

{'and': 1,
 'the': 2,
 'to': 3,
 'apsit': 4,
 'in': 5,
 'by': 6,
 'shah': 7,
 'of': 8,
 'pct': 9,
 'is': 10,
 'aims': 11,
 'world': 12,
 'students': 13,
 'training': 14,
 'a': 15,
 'p': 16,
 'institute': 17,
 'technology': 18,
 'managed': 19,
 'parshvanath': 20,
 'charitable': 21,
 'trust': 22,
 'committed': 23,
 'providing': 24,
 'top': 25,
 'notch': 26,
 'technical': 27,
 'education': 28,
 'founded': 29,
 '1993': 30,
 'late': 31,
 'shri': 32,
 'ashokbhai': 33,
 'offer': 34,
 'class': 35,
 'facilities': 36,
 'an': 37,
 'environment': 38,
 'conducive': 39,
 'learning': 40,
 'boasts': 41,
 'experienced': 42,
 'faculty': 43,
 'exemplary': 44,
 'infrastructure': 45,
 'ensuring': 46,
 'holistic': 47,
 'development': 48,
 'placement': 49,
 'department': 50,
 'facilitates': 51,
 'career': 52,
 'opportunities': 53,
 'organizing': 54,
 'campus': 55,
 'recruitments': 56,
 'offering': 57,
 'soft': 58,
 'skills': 59,
 'aptitude': 60,
 'through': 61,
 'various': 62,
 'activities': 63,
 'programs':

In [ ]:
pos = np.argmax(model.predict(padded_token_text))
for word,index in tokenizer.word_index.items():
    if index == pos:
      print(word)

1/1 [==============================] - 0s 22ms/step
pct


In [ ]:
import time
text = "A P Shah"

for i in range(10):

  token_text = tokenizer.texts_to_sequences([text])[0]

  padded_token_text = pad_sequences([token_text], maxlen=50, padding='pre')

  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 [==============================] - 0s 28ms/step
A P Shah pct
1/1 [==============================] - 0s 27ms/step
A P Shah pct aims
1/1 [==============================] - 0s 31ms/step
A P Shah pct aims to
1/1 [==============================] - 0s 48ms/step
A P Shah pct aims to learning
1/1 [==============================] - 0s 29ms/step
A P Shah pct aims to learning in
1/1 [==============================] - 0s 27ms/step
A P Shah pct aims to learning in the
1/1 [==============================] - 0s 68ms/step
A P Shah pct aims to learning in the training
1/1 [==============================] - 0s 27ms/step
A P Shah pct aims to learning in the training and
1/1 [==============================] - 0s 27ms/step
A P Shah pct aims to learning in the training and industry
1/1 [==============================] - 0s 27ms/step
A P Shah pct aims to learning in the training and industry preparing


In [ ]:

import time
text = "Engineering"

for i in range(10):

  token_text = tokenizer.texts_to_sequences([text])[0]

  padded_token_text = pad_sequences([token_text], maxlen=50, padding='pre')

  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 [==============================] - 0s 44ms/step
Engineering and
1/1 [==============================] - 0s 35ms/step
Engineering and an
1/1 [==============================] - 0s 52ms/step
Engineering and an environment
1/1 [==============================] - 0s 144ms/step
Engineering and an environment conducive
1/1 [==============================] - 0s 26ms/step
Engineering and an environment conducive to
1/1 [==============================] - 0s 26ms/step
Engineering and an environment conducive to learning
1/1 [==============================] - 0s 26ms/step
Engineering and an environment conducive to learning in
1/1 [==============================] - 0s 25ms/step
Engineering and an environment conducive to learning in the
1/1 [==============================] - 0s 44ms/step
Engineering and an environment conducive to learning in the training
1/1 [==============================] - 0s 25ms/step
Engineering and an environment conducive to learning in the training and
